# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.BigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('avatar_hd', models.CharField(max_length=300)),
                ('access_token', models.CharField(max_length=50)),
                ('expires_in', models.BigIntegerField()),
                ('is_admin', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
