# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-03 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=5)),
                ('level', models.IntegerField()),
                ('total', models.BigIntegerField()),
                ('right', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnum', models.IntegerField()),
                ('rightnum', models.IntegerField()),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_qnum', models.IntegerField()),
                ('now_rightnum', models.IntegerField()),
                ('qtime', models.DateTimeField()),
                ('is_finished', models.BooleanField()),
                ('questions', models.ManyToManyField(related_name='quizstatuses', to='quiz.Question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quizstatus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
