# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-04 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option1',
            new_name='optionA',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option2',
            new_name='optionB',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option3',
            new_name='optionC',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option4',
            new_name='optionD',
        ),
    ]
