# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170404_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 9, 11, 46, 49, 491359)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizstatus',
            name='answer',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizstatus',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 9, 11, 47, 4, 291500)),
            preserve_default=False,
        ),
    ]
