# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170409_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizstatus',
            name='answer',
            field=models.CharField(default='', max_length=5),
        ),
    ]
