# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170409_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstatus',
            name='now_qi',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
