# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170409_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizhistory',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='quizstatus',
            name='start_time',
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='use_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizstatus',
            name='use_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
