# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20170409_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizhistory',
            name='use_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizstatus',
            name='use_time',
            field=models.IntegerField(default=0),
        ),
    ]
