# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0008_auto_20170409_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnum', models.IntegerField()),
                ('rightnum', models.IntegerField()),
                ('use_time', models.IntegerField(default=0)),
                ('end_time', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='besthistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
